const almanac = require("../providers/Almanac");

Array.prototype.diff = function(a) {
    return this.filter(function(i) {return a.indexOf(i) < 0;});
};

const list1 = [
    "African Violets",
    "Aloe Vera",
    "Apples",
    "Arugula",
    "Asparagus",
    "Asters",
    "Astilbe",
    "Basil",
    "Bee Balm",
    "Beets",
    "Bell Peppers",
    "Bird of Paradise",
    "Black-eyed Susans",
    "Blackberries",
    "Bleeding Heart",
    "Blueberries",
    "Broccoli",
    "Brussels Sprouts",
    "Butterfly Bush",
    "Cabbage",
    "Cannas",
    "Cantaloupes",
    "Carrots",
    "Cauliflower",
    "Celery",
    "Cherries",
    "Chives",
    "Christmas Cactus",
    "Chrysanthemums",
    "Cilantro (Coriander)",
    "Coleus",
    "Columbine",
    "Coneflowers",
    "Corn",
    "Cosmos",
    "Crocuses",
    "Croton",
    "Cucumbers",
    "Daffodils",
    "Dahlias",
    "Delphiniums",
    "Dill",
    "Edamame",
    "Eggplants",
    "Figs",
    "Foxglove",
    "Garlic",
    "Geraniums",
    "Gladiolus",
    "Grapes",
    "Green Beans",
    "Hibiscus",
    "Horseradish",
    "Hostas",
    "Hyacinth and Muscari",
    "Hydrangeas",
    "Impatiens",
    "Irises",
    "Jade Plants",
    "Jasmine",
    "Kale",
    "Lavender",
    "Lemons & Oranges",
    "Lettuce",
    "Lilacs",
    "Lilies",
    "Lupines",
    "Marigolds",
    "Marjoram",
    "Mint",
    "Morning Glories",
    "Nasturtium",
    "Okra",
    "Onions",
    "Orchids",
    "Oregano",
    "Pansies",
    "Parsley",
    "Parsnips",
    "Peace Lilies",
    "Peaches",
    "Pears",
    "Peas",
    "Peonies",
    "Petunias",
    "Phlox",
    "Plums",
    "Ponytail Palms",
    "Potatoes",
    "Pothos",
    "Pumpkins",
    "Radishes",
    "Raspberries",
    "Rhododendrons",
    "Rhubarb",
    "Rosemary",
    "Roses",
    "Rutabagas",
    "Sage",
    "Salvia",
    "Sedum",
    "Shasta Daisies",
    "Snake Plants",
    "Spider Plants",
    "Spinach",
    "Squash (Zucchini)",
    "Strawberries",
    "Sunflowers",
    "Sweet Peas",
    "Sweet Potatoes",
    "Swiss Chard",
    "Tarragon",
    "Thyme",
    "Tomatoes",
    "Tulips",
    "Turnips",
    "Veronica (Speedwell)",
    "Wandering Jew",
    "Watermelons",
    "Wisteria",
    "Yarrow",
    "Zinnias"
];

almanac.getAllStoredSearches().then(results => {
    // console.log(result);
    const list2 = results.map(r => {
        return r.title.replace("Growing ", "");
    }).sort();

    console.log(list1.diff(list2));
    process.exit();
});